### ISSUE TITLE
Bug in Derived Controllers' constructor 

### ISSUE THREAD

**Issue by jilinzhouas** [astuff/pacmod_game_control#124]
In C++, a new object of derived class will call its based constructor first. With the current code, the unordered_map of `axes_` and `btns_` of a derived controller still holds the key-value pairs of the base class which is incorrect. A simple test program is given as the following: 

```
#include <iostream>
#include <unordered_map>

class Base {
protected:
   std::unordered_map<std::string, int> axes_ = {
    { "JOYAxis::LEFT_STICK_LR", 0 },     { "JoyAxis::LEFT_STICK_UD", 1 },
    { "JoyAxis::RIGHT_STICK_LR", 3 },    { "JoyAxis::RIGHT_STICK_UD", 4 },
    { "JoyAxis::LEFT_TRIGGER_AXIS", 2 }, { "JoyAxis::RIGHT_TRIGGER_AXIS", 5 },
    { "JoyAxis::DPAD_LR", 6 },           { "JoyAxis::DPAD_UD", 7 }
  };
public:
  void print() {
    for (auto const &pair: axes_) {
        std::cout << "{" << pair.first << ": " << pair.second << "}\n";
    }
  }
};

class Derived : public Base {
public:
    Derived() {
      axes_["ABC"] = 8;        
    }
};

int main()
{
    Derived a;
    a.print();
   return 0;
}
```
It gives the output:
```
{ABC: 8}
{JoyAxis::DPAD_UD: 7}
{JoyAxis::DPAD_LR: 6}
{JoyAxis::LEFT_TRIGGER_AXIS: 2}
{JoyAxis::RIGHT_TRIGGER_AXIS: 5}
{JoyAxis::RIGHT_STICK_UD: 4}
{JoyAxis::RIGHT_STICK_LR: 3}
{JoyAxis::LEFT_STICK_UD: 1}
{JOYAxis::LEFT_STICK_LR: 0}
```

If the default key-value pairs are really necessary for the base controller, they should be cleared in the derived class's contructor.

**Comment by icolwell-as** [comment]
This was done intentionally, since some of the buttons are the same for various controllers.
Instead of having to re-define all the buttons for every controller type, you only need to define what is unique/different for that specific controller.
