### ISSUE TITLE
Support more joysticks

### ISSUE THREAD

**Issue by hugomatic** [astuff/pacmod_game_control#21]
Wer'e using the Logitech G920, which is not supported.

Instead of hard coding joysticks, can you instead have parameters in the launch file so we can assign joystick channels manually:

~~~

<arg name="axis_steering" default="0"/>
<arg name="axis_accel" default="1"/>
<arg name="axis_brake" default="2"/>


<node pkg="joy" type="joy_node" name="joy">
  <param name="axis_steering" value="$(arg axis_steering)"/>
  <param name="axis_accel" value="$(arg axis_accel)"/>
  <param name="axis_brake" value="$(arg axis_brake)"/>
  <param name="button_enable" value="6"/>
  <param name="button_disable" value="7"/>
  <param name="button_forward" value="0"/>
  <param name="button_reverse" value="1"/>
  <param name="button_neutral" value="2"/>
</node>
~~~

**Comment by JWhitleyAStuff** [comment]
@hugomatic - While I generally agree with the concept of more configurable parameters being better, I think this one in particular poses a significant safety risk. A single wrong keystroke would likely spell disaster when a vehicle system becomes unexpectedly uncontrollable - especially if this change accidentally gets pushed to a widely-used fork or branch. We are definitely happy to receive and test pull requests with support for new controllers (all it takes now is adding the name to `include/globals.h` and a block to `src/startup_checks.cpp` with the button mapping), but we are not OK with the button mapping being a runtime decision - again, for safety. Would you mind creating a pull request to add support for this controller? We'll get one ourselves to test it out.

**Comment by maximus5684** [comment]
@hugomatic - Please be aware that the version of the firmware that you use does not determine support for physical systems (like wipers). This is determined by the version of PACMod and the associated wiring harness that you have installed in your vehicle and which type vehicle you are using. If this is for a GEM (guessing by your other submitted issue), then wipers are not currently supported. The supported feedback/control systems on Polaris GEMs are:

- Accelerator
- Brake (control and feedback only when enabled)
- Shifting
- Steering
- Turn Indicators / Hazards

In addition, vehicle speed is provided. The GEM control/feedback is currently pretty basic but the vehicles themselves aren't very complicated.
